# # Definitions of tags to detect
#
# ## General remarks
#
# - All length in meters
# - 'size' refers to the length of the shared border between solid black and solid white rectangle.
#   See README.md or https://github.com/AprilRobotics/apriltag/wiki/AprilTag-User-Guide#pose-estimation for details.
# - Ellipsis (...) signifies that the previous element can be repeated multiple times.
#
# ## Standalone tag definitions
# ### Remarks
#
# - name is optional
#
# ### Syntax
#
# standalone_tags:
#   [
#     {id: ID, size: SIZE, name: NAME},
#     ...
#   ]
standalone_tags:
  [
    # {id: 0, size: 0.1},
    # {id: 1, size: 0.1},
    {id: 585, size: 0.192},
  ]
# ## Tag bundle definitions
# ### Remarks
#
# - name is optional
# - x, y, z have default values of 0 thus they are optional
# - qw has default value of 1 and qx, qy, qz have default values of 0 thus they are optional
#
# ### Syntax
#
# tag_bundles:
#   [
#     {
#       name: 'CUSTOM_BUNDLE_NAME',
#       layout:
#         [
#           {id: ID, size: SIZE, x: X_POS, y: Y_POS, z: Z_POS, qw: QUAT_W_VAL, qx: QUAT_X_VAL, qy: QUAT_Y_VAL, qz: QUAT_Z_VAL},
#           ...
#         ]
#     },
#     ...
#   ]
tag_bundles:
  [
    {
      name: 'bundle_0',
      layout:
        [
          {id: 0, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 4, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 3, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 2, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 1, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_1',
      layout:
        [
          {id: 5, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 9, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 8, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 7, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 6, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_2',
      layout:
        [
          {id: 10, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 14, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 13, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 12, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 11, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_3',
      layout:
        [
          {id: 15, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 19, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 18, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 17, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 16, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_4',
      layout:
        [
          {id: 20, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 24, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 23, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 22, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 21, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_5',
      layout:
        [
          {id: 25, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 29, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 28, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 27, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 26, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_6',
      layout:
        [
          {id: 30, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 34, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 33, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 32, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 31, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_7',
      layout:
        [
          {id: 35, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 39, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 38, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 37, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 36, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_8',
      layout:
        [
          {id: 40, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 44, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 43, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 42, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 41, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_9',
      layout:
        [
          {id: 45, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 49, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 48, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 47, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 46, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_10',
      layout:
        [
          {id: 50, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 54, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 53, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 52, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 51, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_11',
      layout:
        [
          {id: 55, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 59, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 58, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 57, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 56, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_12',
      layout:
        [
          {id: 60, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 64, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 63, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 62, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 61, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_13',
      layout:
        [
          {id: 65, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 69, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 68, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 67, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 66, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_14',
      layout:
        [
          {id: 70, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 74, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 73, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 72, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 71, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_15',
      layout:
        [
          {id: 75, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 79, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 78, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 77, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 76, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_16',
      layout:
        [
          {id: 80, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 84, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 83, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 82, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 81, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_17',
      layout:
        [
          {id: 85, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 89, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 88, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 87, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 86, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_18',
      layout:
        [
          {id: 90, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 94, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 93, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 92, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 91, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_19',
      layout:
        [
          {id: 95, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 99, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 98, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 97, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 96, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_114',
      layout:
        [
          {id: 570, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 574, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 573, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 572, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 571, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_115',
      layout:
        [
          {id: 575, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 579, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 578, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 577, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 576, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
    {
      name: 'bundle_116',
      layout:
        [
          {id: 580, size: 0.048, x: 0.0000, y: 0.0000, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 584, size: 0.048, x: 0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 583, size: 0.048, x: -0.06 , y: -0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 582, size: 0.048, x: 0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0},
          {id: 581, size: 0.048, x: -0.06 , y: 0.0605, z: 0.0, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
        ]
    },
  ]
